### PR TITLE
Create Translations

### PR DESCRIPTION
**Pull request by MaiconJunge**
Directory with translations of the Decred Journal.

### CODE REVIEW

**Comment by xaur** [comment]
Hi, I'm seeing an empty file added in that commit.

By the way, all known translations are linked from the home page: https://xaur.github.io/decred-news/

**Comment by MaiconJunge** [comment]
Hi!
Would not it be best to put all .md in a folder within your project?
Thank you!

**Comment by xaur** [comment]
Oh do you mean take all translated .md files and add to this repo?

**Comment by MaiconJunge** [comment]
Right! Will get more organized. All translations into Portuguese would, for example, be found in the folder https://github.com/xaur/decred-news/tree/master/journal/translations/ptbr
Collaborator will upload the translated file. You approve and link on the homepage.

**Comment by Guang168** [comment]
The only potential issue is that the most preferred link may not be a github link but the mirrored link at medium/facebook/weibo or whichever site local community find convenient.

**Comment by MaiconJunge** [comment]
You can also place the other links. But the .MD would be gathered and organized.

**Comment by MaiconJunge** [comment]
Okay, if you need help, just let me know.
Thank you!

**Pull request closed without merging**
