### PR TITLE
Update mirrors.md

### PR DESCRIPTION
**Pull request by DominicTing**

### CODE REVIEW

**Comment by xaur** [comment]
@DominicTing thanks for the PR. Do you know if wechat links can be reduced or are all parts necessary?

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483915&idx=1&sn=f026ae105e661ced2781ef2316463a48&chksm=ce5fb12ef9283838aa4363381ed07be3fc851ae7459de37b6ab7cca0dca36aaaff51677ae4b0&token=2121974069&lang=zh_CN#rd

**Comment by Guang168** [comment]
Seems the shorter link below still works. Not sure if it can be shorten further. 

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483915&idx=1&sn=f026ae105e661ced2781ef2316463a48

**Comment by xaur** [comment]
Reduced URLs from this PR:

Nov

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483663&idx=1&sn=01f72bbe68103ac75ff925f9a6454b84

Dec

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483707&idx=2&sn=48751ad1611063c83ab6001198698c6b

Jan

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483707&idx=1&sn=3d8aace65a89c5c4c3ac104272361116

Feb

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483815&idx=1&sn=137c91ddc51b62cc024a4154236073d3

Mar

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483869&idx=1&sn=e6c2c98781ba94e60ddc10512c38b96c

Apr

https://www.weibo.com/ttarticle/p/show?id=2309404370933585448802

https://mp.weixin.qq.com/s?__biz=Mzg2NTExNzc3MA==&mid=2247483915&idx=1&sn=f026ae105e661ced2781ef2316463a48

**Comment by xaur** [comment]
Additions of this PR moved to #75.

**Pull request closed without merging**
